---

- hosts: django_nginx
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - centos_python36_setup
    - django_project
    - uwsgi
    - nginx
    - dir_ownership
    - firewall
