---

- name: git clone url_shortening repo
  git:
    repo: "{{ django_git_repo }}"
    dest: /opt/url_shortener

- name: pip create virtualenv and install python required modules
  pip:
    requirements: /opt/url_shortener/requirements.txt
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "{{ virtualenv_command }}"

- name: django collectstatic
  django_manage:
    command: "collectstatic --noinput"
    app_path: "{{ django_app_path }}"
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "{{ virtualenv_command }}"
