---

- hosts: all
  remote_user: root

  vars:
    - password:  'f71b0e4e46773be97275c0032fa72fa0498e9c5a1e849d0ebd2fe414882b932d7d0a8e9102beee4d1a5ac111d884123110ead2b7d78585e41e77c960ec9938d6'

  tasks:
    - name: Create a login user
      user:
        name: letstest
        password: {{ password }}
        update_password: on_create
        group: wheel
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/letstest





---

- hosts: all
  remote_user: root

  tasks:
    - name: git clone url_shortening repo
      git:
        repo: https://github.com/svdaniel/url_shortener.git
        dest: /opt/url_shortener

    - name: pip install
      pip:
        requirements: /opt/requirements.txt
        virtualenv: /opt/venv
        virtualenv_command: /usr/bin/python3.6 -m venv
