---

# yum update -y
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: ensure a list of packages installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - make
    - git
    - patch
    - openssl-devel
    - zlib-devel
    - readline-devel
    - sqlite-devel
    - bzip2-devel
    - https://centos7.iuscommunity.org/ius-release.rpm

- name: yum update for ius-release to take effect
  raw: yum clean all


- name: install python3.6
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python36u
    - python36u-pip
    - python36u-devel
