---


- name: install uwsgi
  pip:
    name: "uwsgi"
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "{{ virtualenv_command }}"

- name: configure uwsgi daemon
  template: src=uwsgi.service dest=/etc/systemd/system/

- name: force reload systemd to re-read configs
  systemd:
    daemon_reload: yes

- name: start & enable uwsgi
  systemd:
    name: uwsgi
    state: restarted
    enabled: yes

